'use client';
import Link from 'next/link';
import {motion} from 'framer-motion';
import {FiArrowUpRight,FiArrowRight,FiMapPin,FiShield,FiPackage,FiShoppingBag,FiTruck,FiCoffee,FiNavigation,FiCheck,FiZap} from 'react-icons/fi';
import {FaMotorcycle,FaCarSide} from 'react-icons/fa';
import {serviceGroups} from '@/lib/config';
import {vehicleIcons,groupIcons} from '@/components/vehicle-icons';
import {Reveal,RevealGroup,RevealItem,MotionLink} from '@/components/motion';
import AppHome from '@/components/app-home';
export default function Home(){return <>
<AppHome/>
<section className="hero"><div className="container hero-grid">
<motion.div className="hero-copy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:0.8,ease:[0.16,1,0.3,1]}}>
<p className="eyebrow"><span className="live-dot"/> MADE FOR YOUR EVERYDAY</p><h1>Your city.<br/>One <span className="accent italic">connection.</span></h1><p className="hero-description">From your first ride to your last-minute cravings.<br className="desktop-only"/> Life moves better when it all comes together.</p>
<div className="button-row"><MotionLink whileHover={{scale:1.04}} whileTap={{scale:0.97}} className="button" href="/book">Find your next move <FiArrowUpRight/></MotionLink><Link className="text-link" href="/marketplace">Explore marketplace <FiArrowRight/></Link></div>
<div className="hero-footnote"><FiShield/> Clear requests <span/> PKR pricing <span/> Built for Pakistan</div>
</motion.div>
<motion.div className="hero-scene" aria-label="Illustration of connected city services" initial={{opacity:0,scale:0.94}} animate={{opacity:1,scale:1}} transition={{duration:1,delay:0.15,ease:[0.16,1,0.3,1]}}><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="scene-grid"/><div className="city-base"><div className="road road-one"/><div className="road road-two"/><div className="building b1"/><div className="building b2"/><div className="building b3"/><div className="building b4"/><div className="building b5"/><div className="park"/></div><div className="floating-card ride-float"><span className="service-symbol mint"><FaCarSide/></span><div><small>YOUR NEXT MOVE</small><strong>A smoother way to go</strong><span>Rides, on your terms</span></div><FiArrowUpRight/></div><div className="floating-card food-float"><span className="service-symbol peach"><FiCoffee/></span><div><strong>Cravings? Covered.</strong><span>Discover local favourites</span></div></div><div className="location-pin"><FiMapPin/></div><div className="scene-badge"><FiZap/> One platform. More possibilities.</div><div className="bike-chip"><FaMotorcycle/></div></motion.div>
</div></section>
<Reveal as="div" className="service-strip"><div className="container"><span>ONE ACCOUNT. YOUR WHOLE DAY.</span><span><FaMotorcycle/> Ride</span><span><FiCoffee/> Eat</span><span><FiShoppingBag/> Shop</span><span><FiPackage/> Send</span><span><FiTruck/> Move</span></div></Reveal>
<section className="container section" id="services"><Reveal className="section-heading"><div><p className="eyebrow">OUR SERVICES</p><h2>Pick your ride,<br/>your delivery, your load.</h2></div><p>One thoughtfully connected place<br/>for the things your day needs.</p></Reveal><RevealGroup className="svc-grid">{serviceGroups.map((g,i)=>{const GI=groupIcons[g.id];return <RevealItem key={g.id}><article className="svc-card" style={{'--c':g.color} as React.CSSProperties}><span className="svc-num" aria-hidden="true">0{i+1}</span><div className="svc-top"><span className="svc-icon"><GI aria-hidden="true"/></span><span className="svc-tag">{g.tag}</span></div><h3>{g.title}</h3><p>{g.text}</p><ul className="svc-vehicles">{g.vehicles.map(v=>{const VI=vehicleIcons[v.name];return <li key={v.name}><Link href={'/book?service='+encodeURIComponent(v.name)} title={v.note}><VI aria-hidden="true"/><span><strong>{v.name}</strong><small>{v.note}</small></span><FiArrowUpRight aria-hidden="true"/></Link></li>;})}</ul></article></RevealItem>;})}</RevealGroup></section>
<section className="container"><Reveal className="mission-panel"><div><p className="eyebrow">LOCAL AT HEART. BIG ON POSSIBILITY.</p><h2>A whole city of opportunity.<br/><span className="accent">And a place for you.</span></h2><p>Drive your own journey. Bring your shop online.<br/>Help a neighbourhood move forward.</p><MotionLink whileHover={{scale:1.04}} whileTap={{scale:0.97}} className="button light" href="/partner">Become a partner <FiArrowUpRight/></MotionLink></div><div className="partner-art"><div className="partner-orbit"/><FiNavigation className="partner-icon"/><span className="partner-tag tag-one"><FiCheck/> Drivers & couriers</span><span className="partner-tag tag-two"><FiCheck/> Shops & restaurants</span><span className="partner-tag tag-three"><FiCheck/> Fleet operators</span></div></Reveal></section>
<section className="container section"><RevealGroup className="grid three principles"><RevealItem><article><FiShield/><h3>Trust is a process.</h3><p>Private accounts and explicit booking states. No invented driver locations or fake availability.</p></article></RevealItem><RevealItem><article><FiShoppingBag/><h3>Know what you’re paying.</h3><p>Review your cart and delivery fee before placing a cash-on-delivery order.</p></article></RevealItem><RevealItem><article><FiMapPin/><h3>Start local. Build better.</h3><p>A Pakistan-first pilot. Service coverage grows only when real partners are ready.</p></article></RevealItem></RevealGroup></section>
<section className="container faq-section"><Reveal><p className="eyebrow">GOOD QUESTIONS. CLEAR ANSWERS.</p><h2>A little clarity, before you go.</h2></Reveal>{[['Can I book a ride instantly?','You can submit a request. A real operator must confirm availability; there is no automatic driver matching in this release.'],['Can I pay online?','This release supports cash on delivery only. No online payment or money transfer is collected.'],['Is intercity coach booking confirmed ticketing?','No. It is an enquiry only. There is no Daewoo integration or affiliation.'],['Can I join as a worker or seller?','Yes. Sign in, submit a partner application and track its review in your account. Approval is not a guarantee of work or earnings.']].map(([q,a],i)=><Reveal key={q} delay={i*0.05}><details><summary>{q}</summary><p>{a}</p></details></Reveal>)}</section>
</>;}
