'use client';
import {useEffect,useState,type FormEvent,type CSSProperties} from 'react';
import Link from 'next/link';
import {api} from '@/lib/supabase';
import {serviceGroups,services,groupOf,isEnquiry,type ServiceName} from '@/lib/config';
import {vehicleIcons,groupIcons} from './vehicle-icons';
import {Field,PhoneField,CityField,AddressField,Notice,messageOf} from './form-fields';
export default function BookingForm(){
 const [service,setService]=useState<ServiceName>('Bike'),[group,setGroup]=useState('Rides'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{const selected=new URLSearchParams(window.location.search).get('service');const found=services.find(s=>s===selected);if(found){setService(found);setGroup(groupOf(found)?.id||'Rides');}},[]);
 function pickGroup(id:string){const g=serviceGroups.find(x=>x.id===id);if(!g)return;setGroup(id);if(!g.vehicles.some(v=>v.name===service))setService(g.vehicles[0].name);}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||done)return;setBusy(true);setMessage('');setError(false);const form=new FormData(e.currentTarget);
 try{const data={service,city:form.get('city'),pickup:form.get('pickup'),destination:form.get('destination'),phone:form.get('phone'),offer:form.get('offer')?Number(form.get('offer')):null,notes:form.get('notes')||''};const fingerprint=JSON.stringify(data);const raw=sessionStorage.getItem('raftaar-booking');const previous=raw?JSON.parse(raw):null;const requestId=previous?.fingerprint===fingerprint?previous.id:crypto.randomUUID();sessionStorage.setItem('raftaar-booking',JSON.stringify({fingerprint,id:requestId}));const result=await api('bookings',{...data,requestId});setDone(true);sessionStorage.removeItem('raftaar-booking');setMessage('Request saved. Reference: '+result.id+'. This is not a confirmed ride or ticket. Check your account for operator updates.');
 }catch(err){setMessage(messageOf(err));setError(true);}finally{setBusy(false);}}
 const current=serviceGroups.find(g=>g.id===group)||serviceGroups[0];
 return <div className="account-grid"><section className="panel"><form className="form-stack" onSubmit={submit}>
 <div className="field"><span>What do you need?</span><div className="tabs group-tabs" role="tablist" aria-label="Service category">{serviceGroups.map(g=>{const GI=groupIcons[g.id];return <button type="button" role="tab" aria-selected={g.id===group} key={g.id} className={'tab '+(g.id===group?'active':'')} onClick={()=>pickGroup(g.id)} disabled={done}><GI aria-hidden="true"/> {g.title}</button>;})}</div></div>
 <div className="field"><span>Choose your vehicle · {current.title}</span><div className="vehicle-grid" role="radiogroup" aria-label="Vehicle type">{current.vehicles.map(v=>{const VI=vehicleIcons[v.name];return <button type="button" role="radio" aria-checked={v.name===service} key={v.name} className={'vehicle-option '+(v.name===service?'selected':'')} style={{'--c':current.color} as CSSProperties} onClick={()=>setService(v.name)} disabled={done}><span className="vehicle-icon"><VI aria-hidden="true"/></span><strong>{v.name}</strong><small>{v.note}</small></button>;})}</div></div>
 <div className="grid two"><CityField/><PhoneField/></div><AddressField label="Pickup address / departure city" name="pickup" placeholder="Start typing an area, road or landmark…" hint="Suggestions cover all of Pakistan. Can't find it? Keep typing your own address."/><AddressField label="Destination address / arrival city" name="destination" placeholder="Start typing an area, road or landmark…" hint="Suggestions cover all of Pakistan. Can't find it? Keep typing your own address."/><Field label="Your proposed fare in PKR · optional, not a confirmed quote"><input name="offer" type="number" min="100" max="1000000" step="1" placeholder="For example, 500"/></Field><Field label={isEnquiry(service)?'Notes · route, travel date, number of passengers, preferred operator':'Notes · parcel size, load details, preferred date'}><textarea name="notes" maxLength={500}/></Field><label className="form-note"><input type="checkbox" required/> I understand that availability and fare require operator confirmation.</label><button className="button" disabled={busy||done}>{done?'Request submitted':busy?'Submitting…':'Submit booking request · '+service}</button></form><Notice message={message} error={error}/>{done&&<Link className="text-link" href="/account">Track request in My account</Link>}</section><aside className="panel"><p className="eyebrow">THE ROAD AHEAD</p><h2 style={{fontSize:34}}>A clear request.<br/>A real response.</h2><p style={{marginTop:22}}>Choose a vehicle, enter your locations and submit your request. An operator reviews availability before confirming anything.</p><div className="notice">This release does not automatically dispatch drivers, calculate road distances, share live GPS or issue coach tickets.</div><p className="form-note">Bus and coach requests are generic enquiries, not tickets. Raftaar One has no affiliation with any coach operator, including Daewoo. Do not send advance payments to unknown drivers or share passwords, OTPs or identity documents in notes.</p><p style={{marginTop:20}}><Link className="text-link" href="/account">Sign in or create your account</Link></p></aside></div>;
}
