'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {FiShoppingBag,FiMinus,FiPlus,FiTrash2} from 'react-icons/fi';
import {useCart} from './cart-provider';
import {browserDB,api} from '@/lib/supabase';
import {imageUrl} from '@/lib/images';
import {money} from '@/lib/config';
import type {Product} from '@/lib/types';
import {PhoneField,CityField,AddressField,Notice,messageOf} from './form-fields';
export default function Checkout(){
 const {items,setQuantity,clear,ready}=useCart();const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[success,setSuccess]=useState('');const requestId=useRef('');
 const ids=items.map(i=>i.id).sort().join(',');
 useEffect(()=>{if(!ready)return;async function load(){setLoading(true);try{if(!ids){setProducts([]);return;}const {data,error}=await browserDB().from('products').select('*').in('id',ids.split(','));if(error)throw error;setProducts(data||[]);}catch(err){setMessage(messageOf(err));}finally{setLoading(false);}}void load();},[ids,ready]);
 const subtotal=items.reduce((n,i)=>n+(products.find(p=>p.id===i.id)?.price||0)*i.quantity,0);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMessage('');const form=new FormData(e.currentTarget);
 try{const fingerprint=JSON.stringify({items,expectedTotal:subtotal+150,address:form.get('address'),phone:form.get('phone'),city:form.get('city')});const saved=sessionStorage.getItem('raftaar-checkout');const prior=saved?JSON.parse(saved):null;requestId.current=prior?.fingerprint===fingerprint?prior.id:crypto.randomUUID();sessionStorage.setItem('raftaar-checkout',JSON.stringify({fingerprint,id:requestId.current}));
 const result=await api('orders',{requestId:requestId.current,items,expectedTotal:subtotal+150,address:form.get('address'),phone:form.get('phone'),city:form.get('city')});setSuccess(result.id);clear();sessionStorage.removeItem('raftaar-checkout');
 }catch(err){setMessage(messageOf(err));}finally{setBusy(false);}}
 if(!ready||loading)return <div className="skeleton tall"/>;
 if(success)return <div className="panel empty"><h2>Order request received.</h2><p>Reference: {success}</p><p>Cash on delivery. Fulfilment requires merchant confirmation.</p><Link className="button" href="/account">View your orders</Link></div>;
 if(!items.length)return <div className="panel empty"><FiShoppingBag/><h2>A little room for something good.</h2><p>Your cart is empty.</p><Link className="button" href="/marketplace">Explore marketplace</Link></div>;
 return <div className="account-grid"><section className="panel"><h2 style={{fontSize:28}}>Your bag</h2>{items.map(i=>{const p=products.find(p=>p.id===i.id);return <div className="cart-row" key={i.id}><div className="cart-item">{p?.image_path&&<img className="thumb" src={imageUrl('products',p.image_path)||''} alt=""/>}<div><strong>{p?.name||'Unavailable item'}</strong><p>{p?money(p.price):'Remove this item to continue'}</p></div></div><div className="quantity"><button aria-label={'Reduce '+(p?.name||'item')} onClick={()=>setQuantity(i.id,i.quantity-1)}><FiMinus/></button><span>{i.quantity}</span><button aria-label={'Increase '+(p?.name||'item')} disabled={i.quantity>=20} onClick={()=>setQuantity(i.id,i.quantity+1)}><FiPlus/></button><button aria-label={'Remove '+(p?.name||'item')} onClick={()=>setQuantity(i.id,0)}><FiTrash2/></button></div></div>;})}<div className="total-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="total-row"><span>Delivery · configured pilot fee</span><strong>{money(150)}</strong></div><div className="total-row"><strong>Total</strong><strong>{money(subtotal+150)}</strong></div><p className="form-note">The database verifies stock and recalculates the total. Checkout does not accept client-supplied prices. Pilot prices are tax-inclusive; configure actual tax treatment before launch.</p></section><section className="panel"><h2 style={{fontSize:28,marginBottom:22}}>Where shall it go?</h2><p className="form-note" style={{marginBottom:15}}>Sign in before checkout. Cash on delivery only.</p><form className="form-stack" onSubmit={submit}><CityField/><PhoneField/><AddressField label="Full delivery address" name="address" placeholder="Start typing an area, road or landmark…" minLength={10} maxLength={400} hint="Suggestions cover all of Pakistan. Add house/flat number and floor after picking a match."/><label className="form-note"><input type="checkbox" required/> I reviewed the <Link className="text-link" href="/terms">terms & cancellation notice</Link>.</label><button className="button" disabled={busy||items.some(i=>!products.find(p=>p.id===i.id&&p.active&&p.stock>=i.quantity))}>{busy?'Placing request…':'Place COD order'}</button></form><Notice message={message} error/></section></div>;
}
